- name: install and start mysql
  hosts: devops2
  remote_user: devops
  become: true

  roles:
    - mysql

- name: install unzip
  hosts: Devops3
  remote_user: devops
  become: true

  roles:
   - common

- name: install and start apache2/php/ftp/wordpress
  hosts: Devops3
  remote_user: devops
  become: true

  roles:
   - web
